## regional_npcs.gd
## Static roster of permanent, non-recruitable NPCs per subregion map.
## See REGIONAL_NPCS_DESIGN.md and HANDOFF.md for the authoring workflow.
class_name RegionalNpcs
extends RefCounted

# Silver ring tint for regional regulars (distinct from random=gold, named=cyan)
const REGIONAL_TINT: Color = Color(0.82, 0.85, 0.92)

const REGIONAL_NPCS: Dictionary = {

	# ══════════════════════════════════════════════════════════════════════════
	# METROPOLITAN — Urban-peak tier (10 NPCs each)
	# ══════════════════════════════════════════════════════════════════════════

	"Upper Forty": [
		{"id": "uf_caelia_vex", "name": "Caelia Vex", "lineage": "Gilded Human", "role": "court gossip", "recruitable": false,
			"portrait_tint": Color(0.95, 0.82, 0.55),
			"schedule": {6: Vector2i(18, 3), 12: Vector2i(17, 5), 18: Vector2i(21, 14), 0: Vector2i(18, 13)},
			"dialogue_tree_id": "uf_caelia_default", "quest_hooks": ["uf_court_intrigue"]},
		{"id": "uf_master_corin", "name": "Master Corin", "lineage": "Arcanite Human", "role": "academy lecturer", "recruitable": false,
			"portrait_tint": Color(0.70, 0.65, 0.90),
			"schedule": {6: Vector2i(17, 17), 12: Vector2i(19, 17), 18: Vector2i(24, 6), 0: Vector2i(3, 14)},
			"dialogue_tree_id": "uf_corin_default", "quest_hooks": []},
		{"id": "uf_sgt_ardal", "name": "Sgt. Ardal Stonewall", "lineage": "Cragborn Human", "role": "guard captain", "recruitable": false,
			"portrait_tint": Color(0.60, 0.70, 0.75),
			"schedule": {6: Vector2i(7, 5), 12: Vector2i(17, 5), 18: Vector2i(25, 21), 0: Vector2i(8, 5)},
			"dialogue_tree_id": "uf_ardal_default", "quest_hooks": ["uf_night_patrol_trouble"]},
		{"id": "uf_vixi_sparks", "name": "Vixi \"Sparks\"", "lineage": "Nimbari", "role": "gadget merchant", "recruitable": false,
			"portrait_tint": Color(0.90, 0.75, 0.30),
			"schedule": {6: Vector2i(21, 9), 12: Vector2i(5, 9), 18: Vector2i(10, 19), 0: Vector2i(3, 1)},
			"dialogue_tree_id": "uf_vixi_default", "quest_hooks": []},
		{"id": "uf_elder_teros", "name": "Elder Teros", "lineage": "Boreal Human", "role": "retired judge", "recruitable": false,
			"portrait_tint": Color(0.70, 0.60, 0.55),
			"schedule": {6: Vector2i(3, 17), 12: Vector2i(6, 6), 18: Vector2i(4, 21), 0: Vector2i(4, 17)},
			"dialogue_tree_id": "uf_teros_default", "quest_hooks": ["uf_court_intrigue"]},
		{"id": "uf_lyra_moonshadow", "name": "Lyra Moonshadow", "lineage": "Duskling", "role": "information broker", "recruitable": false,
			"portrait_tint": Color(0.45, 0.40, 0.65),
			"schedule": {6: Vector2i(4, 14), 12: Vector2i(22, 14), 18: Vector2i(18, 10), 0: Vector2i(18, 19)},
			"dialogue_tree_id": "uf_lyra_default", "quest_hooks": ["uf_cipher_in_the_grape"]},
		{"id": "uf_brendan_coppervein", "name": "Brendan Coppervein", "lineage": "Argent Dvarrim", "role": "mint clerk", "recruitable": false,
			"portrait_tint": Color(0.85, 0.60, 0.30),
			"schedule": {6: Vector2i(18, 8), 12: Vector2i(17, 8), 18: Vector2i(3, 13), 0: Vector2i(5, 13)},
			"dialogue_tree_id": "uf_brendan_default", "quest_hooks": []},
		{"id": "uf_sister_avella", "name": "Sister Avella", "lineage": "Gilded Human", "role": "almsgiver", "recruitable": false,
			"portrait_tint": Color(0.92, 0.90, 0.70),
			"schedule": {6: Vector2i(7, 8), 12: Vector2i(3, 17), 18: Vector2i(8, 14), 0: Vector2i(17, 10)},
			"dialogue_tree_id": "uf_avella_default", "quest_hooks": ["uf_orphans_missing"]},
		{"id": "uf_magister_hollo", "name": "Magister Hollo", "lineage": "Glimmerfolk", "role": "academy magister", "recruitable": false,
			"portrait_tint": Color(0.60, 0.80, 0.95),
			"schedule": {6: Vector2i(20, 17), 12: Vector2i(19, 10), 18: Vector2i(25, 6), 0: Vector2i(22, 17)},
			"dialogue_tree_id": "uf_hollo_default", "quest_hooks": []},
		{"id": "uf_pip_the_urchin", "name": "Pip the Urchin", "lineage": "Ferrusk", "role": "street kid", "recruitable": false,
			"portrait_tint": Color(0.55, 0.50, 0.40),
			"schedule": {6: Vector2i(22, 9), 12: Vector2i(25, 21), 18: Vector2i(3, 14), 0: Vector2i(4, 6)},
			"dialogue_tree_id": "uf_pip_default", "quest_hooks": ["uf_orphans_missing"]},
	],

	"Lower Forty": [
		{"id": "lf_foreman_hax", "name": "Foreman Hax", "lineage": "Argent Dvarrim", "role": "steel foreman", "recruitable": false,
			"portrait_tint": Color(0.80, 0.45, 0.25),
			"schedule": {6: Vector2i(13, 5), 12: Vector2i(4, 6), 18: Vector2i(8, 10), 0: Vector2i(8, 20)},
			"dialogue_tree_id": "lf_hax_default", "quest_hooks": ["lf_foundry_accident"]},
		{"id": "lf_riveted_vael", "name": "Riveted Vael", "lineage": "Nimbari", "role": "machinist", "recruitable": false,
			"portrait_tint": Color(0.75, 0.65, 0.30),
			"schedule": {6: Vector2i(13, 5), 12: Vector2i(20, 6), 18: Vector2i(22, 8), 0: Vector2i(22, 13)},
			"dialogue_tree_id": "lf_vael_default", "quest_hooks": []},
		{"id": "lf_smokey_jass", "name": "\"Smokey\" Jass", "lineage": "Ferrusk", "role": "ex-miner", "recruitable": false,
			"portrait_tint": Color(0.55, 0.45, 0.40),
			"schedule": {6: Vector2i(7, 2), 12: Vector2i(8, 9), 18: Vector2i(23, 12), 0: Vector2i(8, 17)},
			"dialogue_tree_id": "lf_jass_default", "quest_hooks": []},
		{"id": "lf_magister_yonne", "name": "Magister Yonne", "lineage": "Gilded Human", "role": "mine inspector", "recruitable": false,
			"portrait_tint": Color(0.92, 0.88, 0.70),
			"schedule": {6: Vector2i(9, 9), 12: Vector2i(13, 5), 18: Vector2i(4, 6), 0: Vector2i(8, 17)},
			"dialogue_tree_id": "lf_yonne_default", "quest_hooks": ["lf_foundry_accident"]},
		{"id": "lf_gritta_pipe", "name": "Gritta Pipe", "lineage": "Argent Dvarrim", "role": "smokestack worker", "recruitable": false,
			"portrait_tint": Color(0.65, 0.50, 0.35),
			"schedule": {6: Vector2i(7, 2), 12: Vector2i(22, 13), 18: Vector2i(23, 12), 0: Vector2i(8, 20)},
			"dialogue_tree_id": "lf_gritta_default", "quest_hooks": []},
		{"id": "lf_sooty_mara", "name": "Sooty Mara", "lineage": "Ferrusk", "role": "scavenger kid", "recruitable": false,
			"portrait_tint": Color(0.40, 0.38, 0.35),
			"schedule": {6: Vector2i(22, 8), 12: Vector2i(3, 21), 18: Vector2i(22, 13), 0: Vector2i(4, 2)},
			"dialogue_tree_id": "lf_mara_default", "quest_hooks": ["lf_scavenger_ring"]},
		{"id": "lf_captain_rathe", "name": "Captain Rathe", "lineage": "Cragborn Human", "role": "undercity guard", "recruitable": false,
			"portrait_tint": Color(0.55, 0.65, 0.70),
			"schedule": {6: Vector2i(8, 9), 12: Vector2i(15, 11), 18: Vector2i(25, 4), 0: Vector2i(8, 9)},
			"dialogue_tree_id": "lf_rathe_default", "quest_hooks": ["lf_scavenger_ring"]},
		{"id": "lf_the_whisperer", "name": "The Whisperer", "lineage": "Duskling", "role": "informant", "recruitable": false,
			"portrait_tint": Color(0.35, 0.35, 0.55),
			"schedule": {6: Vector2i(8, 16), 12: Vector2i(22, 13), 18: Vector2i(8, 19), 0: Vector2i(24, 21)},
			"dialogue_tree_id": "lf_whisperer_default", "quest_hooks": []},
		{"id": "lf_bard_anvil", "name": "Bard of the Anvil", "lineage": "Boreal Human", "role": "tavern bard", "recruitable": false,
			"portrait_tint": Color(0.85, 0.70, 0.50),
			"schedule": {6: Vector2i(22, 13), 12: Vector2i(8, 16), 18: Vector2i(8, 19), 0: Vector2i(8, 19)},
			"dialogue_tree_id": "lf_bard_default", "quest_hooks": []},
		{"id": "lf_sister_brall", "name": "Sister Brall", "lineage": "Gilded Human", "role": "almshouse keeper", "recruitable": false,
			"portrait_tint": Color(0.88, 0.85, 0.72),
			"schedule": {6: Vector2i(8, 16), 12: Vector2i(3, 21), 18: Vector2i(8, 16), 0: Vector2i(8, 16)},
			"dialogue_tree_id": "lf_brall_default", "quest_hooks": []},
	],

	"Eternal Library": [
		{"id": "el_archivist_vellum", "name": "Archivist Vellum", "lineage": "Arcanite Human", "role": "head archivist", "recruitable": false,
			"portrait_tint": Color(0.70, 0.55, 0.85),
			"schedule": {6: Vector2i(8, 6), 12: Vector2i(14, 11), 18: Vector2i(15, 2), 0: Vector2i(11, 2)},
			"dialogue_tree_id": "el_vellum_default", "quest_hooks": ["el_missing_manuscript"]},
		{"id": "el_scribe_quill", "name": "Scribe Quill", "lineage": "Glimmerfolk", "role": "copyist", "recruitable": false,
			"portrait_tint": Color(0.75, 0.85, 0.95),
			"schedule": {6: Vector2i(15, 2), 12: Vector2i(17, 2), 18: Vector2i(6, 3), 0: Vector2i(8, 17)},
			"dialogue_tree_id": "el_quill_default", "quest_hooks": []},
		{"id": "el_master_thorne", "name": "Master Thorne", "lineage": "Elf", "role": "forbidden-text scholar", "recruitable": false,
			"portrait_tint": Color(0.50, 0.45, 0.70),
			"schedule": {6: Vector2i(7, 8), 12: Vector2i(8, 7), 18: Vector2i(22, 16), 0: Vector2i(8, 8)},
			"dialogue_tree_id": "el_thorne_default", "quest_hooks": ["el_forbidden_lore"]},
		{"id": "el_young_heidi", "name": "Young Heidi", "lineage": "Ferrusk", "role": "apprentice", "recruitable": false,
			"portrait_tint": Color(0.70, 0.60, 0.45),
			"schedule": {6: Vector2i(11, 2), 12: Vector2i(22, 6), 18: Vector2i(8, 17), 0: Vector2i(6, 3)},
			"dialogue_tree_id": "el_heidi_default", "quest_hooks": []},
		{"id": "el_librarian_dross", "name": "Librarian Dross", "lineage": "Argent Dvarrim", "role": "stern librarian", "recruitable": false,
			"portrait_tint": Color(0.55, 0.50, 0.40),
			"schedule": {6: Vector2i(14, 11), 12: Vector2i(11, 2), 18: Vector2i(6, 3), 0: Vector2i(14, 11)},
			"dialogue_tree_id": "el_dross_default", "quest_hooks": []},
		{"id": "el_mystery_patron", "name": "The Hooded Patron", "lineage": "Duskling", "role": "mystery reader", "recruitable": false,
			"portrait_tint": Color(0.30, 0.30, 0.50),
			"schedule": {6: Vector2i(7, 8), 12: Vector2i(22, 6), 18: Vector2i(8, 7), 0: Vector2i(22, 16)},
			"dialogue_tree_id": "el_patron_default", "quest_hooks": ["el_forbidden_lore"]},
		{"id": "el_cartographer_reis", "name": "Cartographer Reis", "lineage": "Bramblekin", "role": "mapmaker", "recruitable": false,
			"portrait_tint": Color(0.65, 0.80, 0.55),
			"schedule": {6: Vector2i(6, 3), 12: Vector2i(8, 6), 18: Vector2i(22, 6), 0: Vector2i(8, 17)},
			"dialogue_tree_id": "el_reis_default", "quest_hooks": []},
		{"id": "el_brother_bind", "name": "Brother Bind", "lineage": "Arcanite Human", "role": "book binder", "recruitable": false,
			"portrait_tint": Color(0.60, 0.50, 0.65),
			"schedule": {6: Vector2i(24, 19), 12: Vector2i(24, 19), 18: Vector2i(11, 2), 0: Vector2i(8, 17)},
			"dialogue_tree_id": "el_bind_default", "quest_hooks": []},
		{"id": "el_lady_marcellia", "name": "Lady Marcellia", "lineage": "Gilded Human", "role": "philanthropist", "recruitable": false,
			"portrait_tint": Color(0.95, 0.85, 0.65),
			"schedule": {6: Vector2i(14, 11), 12: Vector2i(11, 2), 18: Vector2i(22, 16), 0: Vector2i(22, 16)},
			"dialogue_tree_id": "el_marcellia_default", "quest_hooks": ["el_missing_manuscript"]},
		{"id": "el_the_wanderer", "name": "The Wanderer", "lineage": "Fae-Touched Human", "role": "mysterious visitor", "recruitable": false,
			"portrait_tint": Color(0.50, 0.70, 0.85),
			"schedule": {6: Vector2i(11, 2), 12: Vector2i(14, 11), 18: Vector2i(8, 17), 0: Vector2i(7, 8)},
			"dialogue_tree_id": "el_wanderer_default", "quest_hooks": []},
	],

	"West End Gullet": [
		{"id": "weg_echo_caldera", "name": "Echo Caldera", "lineage": "Fae-Touched Human", "role": "fountain keeper", "recruitable": false,
			"portrait_tint": Color(0.55, 0.75, 0.85),
			"schedule": {6: Vector2i(15, 10), 12: Vector2i(8, 13), 18: Vector2i(14, 19), 0: Vector2i(15, 10)},
			"dialogue_tree_id": "weg_echo_default", "quest_hooks": ["weg_mirror_curse"]},
		{"id": "weg_mirrorwright_sint", "name": "Mirrorwright Sint", "lineage": "Duskling", "role": "mirror merchant", "recruitable": false,
			"portrait_tint": Color(0.60, 0.55, 0.75),
			"schedule": {6: Vector2i(8, 13), 12: Vector2i(24, 8), 18: Vector2i(8, 13), 0: Vector2i(14, 19)},
			"dialogue_tree_id": "weg_sint_default", "quest_hooks": ["weg_mirror_curse"]},
		{"id": "weg_off_shadow", "name": "The Off-Shadow", "lineage": "Duskling", "role": "underground contact", "recruitable": false,
			"portrait_tint": Color(0.30, 0.30, 0.45),
			"schedule": {6: Vector2i(6, 6), 12: Vector2i(14, 19), 18: Vector2i(8, 13), 0: Vector2i(22, 4)},
			"dialogue_tree_id": "weg_shadow_default", "quest_hooks": []},
		{"id": "weg_wrong_way_brix", "name": "Wrong-Way Brix", "lineage": "Ferrusk", "role": "confused guide", "recruitable": false,
			"portrait_tint": Color(0.70, 0.55, 0.40),
			"schedule": {6: Vector2i(15, 10), 12: Vector2i(6, 6), 18: Vector2i(11, 6), 0: Vector2i(14, 19)},
			"dialogue_tree_id": "weg_brix_default", "quest_hooks": []},
		{"id": "weg_sovereigns_herald", "name": "The Sovereign's Herald", "lineage": "Gilded Human", "role": "keep announcer", "recruitable": false,
			"portrait_tint": Color(0.85, 0.70, 0.60),
			"schedule": {6: Vector2i(14, 11), 12: Vector2i(15, 10), 18: Vector2i(22, 4), 0: Vector2i(14, 11)},
			"dialogue_tree_id": "weg_herald_default", "quest_hooks": []},
		{"id": "weg_aunt_malbena", "name": "Aunt Malbena", "lineage": "Gilded Human", "role": "angled-house owner", "recruitable": false,
			"portrait_tint": Color(0.80, 0.72, 0.58),
			"schedule": {6: Vector2i(5, 4), 12: Vector2i(5, 4), 18: Vector2i(8, 13), 0: Vector2i(5, 4)},
			"dialogue_tree_id": "weg_malbena_default", "quest_hooks": []},
		{"id": "weg_silent_tom", "name": "Silent Tom", "lineage": "Boreal Human", "role": "mute musician", "recruitable": false,
			"portrait_tint": Color(0.65, 0.60, 0.55),
			"schedule": {6: Vector2i(14, 19), 12: Vector2i(14, 19), 18: Vector2i(14, 19), 0: Vector2i(8, 13)},
			"dialogue_tree_id": "weg_tom_default", "quest_hooks": []},
		{"id": "weg_echoing_choir", "name": "The Echoing Choir", "lineage": "Fae-Touched Human", "role": "fountain priest", "recruitable": false,
			"portrait_tint": Color(0.60, 0.80, 0.90),
			"schedule": {6: Vector2i(15, 10), 12: Vector2i(22, 4), 18: Vector2i(15, 10), 0: Vector2i(15, 10)},
			"dialogue_tree_id": "weg_choir_default", "quest_hooks": ["weg_mirror_curse"]},
		{"id": "weg_twisted_smith_gor", "name": "Twisted Smith Gor", "lineage": "Cragborn Human", "role": "off-kilter smith", "recruitable": false,
			"portrait_tint": Color(0.65, 0.50, 0.40),
			"schedule": {6: Vector2i(24, 8), 12: Vector2i(24, 8), 18: Vector2i(14, 19), 0: Vector2i(24, 8)},
			"dialogue_tree_id": "weg_gor_default", "quest_hooks": []},
		{"id": "weg_moth_lan", "name": "Moth Lan", "lineage": "Nimbari", "role": "lamp seller", "recruitable": false,
			"portrait_tint": Color(0.75, 0.70, 0.45),
			"schedule": {6: Vector2i(8, 13), 12: Vector2i(8, 13), 18: Vector2i(15, 10), 0: Vector2i(14, 19)},
			"dialogue_tree_id": "weg_lan_default", "quest_hooks": []},
	],

	"Cradling Depths": [
		{"id": "cd_oracle_seris", "name": "High Oracle Seris", "lineage": "Aetherian", "role": "oracle", "recruitable": false,
			"portrait_tint": Color(0.85, 0.85, 1.0),
			"schedule": {6: Vector2i(11, 6), 12: Vector2i(15, 10), 18: Vector2i(11, 6), 0: Vector2i(14, 11)},
			"dialogue_tree_id": "cd_seris_default", "quest_hooks": ["cd_oracle_vision"]},
		{"id": "cd_priest_aelan", "name": "Priest Aelan", "lineage": "Gilded Human", "role": "temple priest", "recruitable": false,
			"portrait_tint": Color(0.95, 0.90, 0.75),
			"schedule": {6: Vector2i(14, 4), 12: Vector2i(14, 11), 18: Vector2i(14, 19), 0: Vector2i(14, 4)},
			"dialogue_tree_id": "cd_aelan_default", "quest_hooks": []},
		{"id": "cd_crystalkeeper_bel", "name": "Crystalkeeper Bel", "lineage": "Argent Dvarrim", "role": "crystal guardian", "recruitable": false,
			"portrait_tint": Color(0.75, 0.85, 0.95),
			"schedule": {6: Vector2i(5, 4), 12: Vector2i(6, 6), 18: Vector2i(24, 8), 0: Vector2i(5, 4)},
			"dialogue_tree_id": "cd_bel_default", "quest_hooks": []},
		{"id": "cd_ichor_kira", "name": "Ichor-Touched Kira", "lineage": "Fae-Touched Human", "role": "blessed one", "recruitable": false,
			"portrait_tint": Color(0.70, 0.85, 0.80),
			"schedule": {6: Vector2i(21, 4), 12: Vector2i(15, 10), 18: Vector2i(8, 13), 0: Vector2i(11, 6)},
			"dialogue_tree_id": "cd_kira_default", "quest_hooks": ["cd_ichor_blessing"]},
		{"id": "cd_lightsmith_odam", "name": "Lightsmith Odam", "lineage": "Cragborn Human", "role": "forge priest", "recruitable": false,
			"portrait_tint": Color(0.90, 0.80, 0.55),
			"schedule": {6: Vector2i(24, 8), 12: Vector2i(24, 8), 18: Vector2i(14, 19), 0: Vector2i(24, 8)},
			"dialogue_tree_id": "cd_odam_default", "quest_hooks": []},
		{"id": "cd_chorister_len", "name": "Chorister Len", "lineage": "Glimmerfolk", "role": "cathedral singer", "recruitable": false,
			"portrait_tint": Color(0.80, 0.90, 1.0),
			"schedule": {6: Vector2i(14, 4), 12: Vector2i(14, 11), 18: Vector2i(14, 4), 0: Vector2i(14, 19)},
			"dialogue_tree_id": "cd_len_default", "quest_hooks": []},
		{"id": "cd_pilgrim_zara", "name": "Pilgrim Zara", "lineage": "Boreal Human", "role": "visiting pilgrim", "recruitable": false,
			"portrait_tint": Color(0.75, 0.70, 0.65),
			"schedule": {6: Vector2i(11, 6), 12: Vector2i(6, 6), 18: Vector2i(8, 13), 0: Vector2i(14, 19)},
			"dialogue_tree_id": "cd_zara_default", "quest_hooks": []},
		{"id": "cd_sister_clarity", "name": "Sister Clarity", "lineage": "Gilded Human", "role": "sanctuary keeper", "recruitable": false,
			"portrait_tint": Color(0.92, 0.92, 0.85),
			"schedule": {6: Vector2i(14, 11), 12: Vector2i(14, 11), 18: Vector2i(14, 19), 0: Vector2i(14, 11)},
			"dialogue_tree_id": "cd_clarity_default", "quest_hooks": []},
		{"id": "cd_abbot_brendai", "name": "Abbot Brendai", "lineage": "Arcanite Human", "role": "old abbot", "recruitable": false,
			"portrait_tint": Color(0.70, 0.65, 0.75),
			"schedule": {6: Vector2i(14, 4), 12: Vector2i(11, 6), 18: Vector2i(14, 11), 0: Vector2i(14, 4)},
			"dialogue_tree_id": "cd_brendai_default", "quest_hooks": ["cd_oracle_vision"]},
		{"id": "cd_veiled_one", "name": "The Veiled One", "lineage": "Duskling", "role": "mysterious oracle", "recruitable": false,
			"portrait_tint": Color(0.40, 0.40, 0.60),
			"schedule": {6: Vector2i(6, 6), 12: Vector2i(11, 6), 18: Vector2i(15, 10), 0: Vector2i(14, 19)},
			"dialogue_tree_id": "cd_veiled_default", "quest_hooks": []},
	],

	# ══════════════════════════════════════════════════════════════════════════
	# THE PLAINS — 8 capital, 8 arena, 6 wild, 6 fey
	# ══════════════════════════════════════════════════════════════════════════

	"Kingdom of Qunorum": [
		{"id": "kq_captain_elwyn", "name": "Captain Elwyn", "lineage": "Cragborn Human", "role": "guard captain", "recruitable": false,
			"portrait_tint": Color(0.60, 0.70, 0.75),
			"schedule": {6: Vector2i(7, 6), 12: Vector2i(15, 9), 18: Vector2i(22, 17), 0: Vector2i(7, 6)},
			"dialogue_tree_id": "kq_elwyn_default", "quest_hooks": ["kq_border_incursion"]},
		{"id": "kq_wizard_meridon", "name": "Royal Wizard Meridon", "lineage": "Arcanite Human", "role": "royal wizard", "recruitable": false,
			"portrait_tint": Color(0.55, 0.55, 0.85),
			"schedule": {6: Vector2i(13, 10), 12: Vector2i(15, 9), 18: Vector2i(8, 17), 0: Vector2i(13, 10)},
			"dialogue_tree_id": "kq_meridon_default", "quest_hooks": []},
		{"id": "kq_knight_tavis", "name": "Knight-Errant Tavis", "lineage": "Boreal Human", "role": "knight-errant", "recruitable": false,
			"portrait_tint": Color(0.85, 0.75, 0.55),
			"schedule": {6: Vector2i(6, 6), 12: Vector2i(22, 12), 18: Vector2i(22, 17), 0: Vector2i(8, 17)},
			"dialogue_tree_id": "kq_tavis_default", "quest_hooks": ["kq_border_incursion"]},
		{"id": "kq_merchant_isolda", "name": "Merchant Queen Isolda", "lineage": "Gilded Human", "role": "caravan mistress", "recruitable": false,
			"portrait_tint": Color(0.95, 0.80, 0.55),
			"schedule": {6: Vector2i(22, 12), 12: Vector2i(15, 9), 18: Vector2i(22, 17), 0: Vector2i(22, 12)},
			"dialogue_tree_id": "kq_isolda_default", "quest_hooks": []},
		{"id": "kq_priestess_ailin", "name": "High Priestess Ailin", "lineage": "Aetherian", "role": "high priestess", "recruitable": false,
			"portrait_tint": Color(0.85, 0.90, 1.0),
			"schedule": {6: Vector2i(7, 14), 12: Vector2i(7, 14), 18: Vector2i(8, 17), 0: Vector2i(7, 14)},
			"dialogue_tree_id": "kq_ailin_default", "quest_hooks": ["kq_prophecy_doubt"]},
		{"id": "kq_squire_perrin", "name": "Squire Perrin", "lineage": "Ferrusk", "role": "eager squire", "recruitable": false,
			"portrait_tint": Color(0.70, 0.60, 0.45),
			"schedule": {6: Vector2i(5, 5), 12: Vector2i(7, 6), 18: Vector2i(22, 17), 0: Vector2i(5, 5)},
			"dialogue_tree_id": "kq_perrin_default", "quest_hooks": []},
		{"id": "kq_smith_kenneth", "name": "Smith Kenneth", "lineage": "Argent Dvarrim", "role": "royal smith", "recruitable": false,
			"portrait_tint": Color(0.75, 0.55, 0.35),
			"schedule": {6: Vector2i(22, 18), 12: Vector2i(22, 18), 18: Vector2i(22, 17), 0: Vector2i(22, 18)},
			"dialogue_tree_id": "kq_kenneth_default", "quest_hooks": []},
		{"id": "kq_old_grayson", "name": "Old Grayson", "lineage": "Boreal Human", "role": "tavern keeper", "recruitable": false,
			"portrait_tint": Color(0.80, 0.70, 0.60),
			"schedule": {6: Vector2i(22, 17), 12: Vector2i(22, 17), 18: Vector2i(22, 17), 0: Vector2i(22, 17)},
			"dialogue_tree_id": "kq_grayson_default", "quest_hooks": ["kq_prophecy_doubt"]},
	],

	"Wilds of Endero": [
		{"id": "we_chief_brushwalker", "name": "Chief Brushwalker", "lineage": "Bramblekin", "role": "tribal chief", "recruitable": false,
			"portrait_tint": Color(0.50, 0.70, 0.40),
			"schedule": {6: Vector2i(4, 6), 12: Vector2i(14, 8), 18: Vector2i(14, 16), 0: Vector2i(4, 6)},
			"dialogue_tree_id": "we_brushwalker_default", "quest_hooks": ["we_beast_lord"]},
		{"id": "we_druid_oren", "name": "Druid Oren", "lineage": "Elf", "role": "druid circle keeper", "recruitable": false,
			"portrait_tint": Color(0.60, 0.80, 0.55),
			"schedule": {6: Vector2i(13, 9), 12: Vector2i(16, 11), 18: Vector2i(14, 16), 0: Vector2i(13, 9)},
			"dialogue_tree_id": "we_oren_default", "quest_hooks": []},
		{"id": "we_beast_talker_rysa", "name": "Beast-Talker Rysa", "lineage": "Ferrusk", "role": "creature handler", "recruitable": false,
			"portrait_tint": Color(0.65, 0.55, 0.40),
			"schedule": {6: Vector2i(5, 2), 12: Vector2i(4, 6), 18: Vector2i(24, 19), 0: Vector2i(5, 2)},
			"dialogue_tree_id": "we_rysa_default", "quest_hooks": ["we_beast_lord"]},
		{"id": "we_hunter_kell", "name": "Hunter Kell", "lineage": "Boreal Human", "role": "tracker", "recruitable": false,
			"portrait_tint": Color(0.70, 0.60, 0.50),
			"schedule": {6: Vector2i(5, 1), 12: Vector2i(22, 9), 18: Vector2i(22, 12), 0: Vector2i(22, 12)},
			"dialogue_tree_id": "we_kell_default", "quest_hooks": []},
		{"id": "we_ring_keeper_anise", "name": "Ring-Keeper Anise", "lineage": "Fae-Touched Human", "role": "stone ring priestess", "recruitable": false,
			"portrait_tint": Color(0.65, 0.75, 0.90),
			"schedule": {6: Vector2i(16, 11), 12: Vector2i(13, 9), 18: Vector2i(16, 11), 0: Vector2i(16, 11)},
			"dialogue_tree_id": "we_anise_default", "quest_hooks": []},
		{"id": "we_bard_jonn", "name": "Wandering Jonn", "lineage": "Boreal Human", "role": "wandering bard", "recruitable": false,
			"portrait_tint": Color(0.85, 0.75, 0.60),
			"schedule": {6: Vector2i(22, 12), 12: Vector2i(14, 8), 18: Vector2i(14, 16), 0: Vector2i(22, 12)},
			"dialogue_tree_id": "we_jonn_default", "quest_hooks": []},
	],

	"Forest of SubEden": [
		{"id": "fs_moonspeaker_lyna", "name": "Moonspeaker Lyna", "lineage": "Elf", "role": "moon priestess", "recruitable": false,
			"portrait_tint": Color(0.70, 0.80, 0.95),
			"schedule": {6: Vector2i(6, 2), 12: Vector2i(14, 1), 18: Vector2i(14, 17), 0: Vector2i(6, 2)},
			"dialogue_tree_id": "fs_lyna_default", "quest_hooks": ["fs_moonwell_tainted"]},
		{"id": "fs_queen_thistledown", "name": "Queen Thistledown", "lineage": "Fae-Touched Human", "role": "fairy queen", "recruitable": false,
			"portrait_tint": Color(0.90, 0.70, 0.85),
			"schedule": {6: Vector2i(17, 8), 12: Vector2i(17, 8), 18: Vector2i(12, 11), 0: Vector2i(17, 8)},
			"dialogue_tree_id": "fs_thistledown_default", "quest_hooks": []},
		{"id": "fs_ancient_yew", "name": "The Ancient Yew", "lineage": "Bramblekin", "role": "treant elder", "recruitable": false,
			"portrait_tint": Color(0.45, 0.60, 0.35),
			"schedule": {6: Vector2i(12, 11), 12: Vector2i(12, 11), 18: Vector2i(12, 11), 0: Vector2i(12, 11)},
			"dialogue_tree_id": "fs_yew_default", "quest_hooks": ["fs_moonwell_tainted"]},
		{"id": "fs_enchanter_sylvios", "name": "Enchanter Sylvios", "lineage": "Glimmerfolk", "role": "enchanter", "recruitable": false,
			"portrait_tint": Color(0.75, 0.90, 0.80),
			"schedule": {6: Vector2i(7, 3), 12: Vector2i(22, 8), 18: Vector2i(24, 13), 0: Vector2i(7, 3)},
			"dialogue_tree_id": "fs_sylvios_default", "quest_hooks": []},
		{"id": "fs_whisper_eluin", "name": "Whisper Eluin", "lineage": "Elf", "role": "forest scout", "recruitable": false,
			"portrait_tint": Color(0.55, 0.70, 0.55),
			"schedule": {6: Vector2i(14, 1), 12: Vector2i(12, 19), 18: Vector2i(22, 11), 0: Vector2i(12, 19)},
			"dialogue_tree_id": "fs_eluin_default", "quest_hooks": []},
		{"id": "fs_spirit_rose", "name": "Spirit-Touched Rose", "lineage": "Fae-Touched Human", "role": "seer", "recruitable": false,
			"portrait_tint": Color(0.85, 0.75, 0.95),
			"schedule": {6: Vector2i(14, 17), 12: Vector2i(17, 8), 18: Vector2i(14, 17), 0: Vector2i(6, 2)},
			"dialogue_tree_id": "fs_rose_default", "quest_hooks": []},
	],

	"Mortal Arena": [
		{"id": "ma_champion_marcus", "name": "Champion Marcus", "lineage": "Cragborn Human", "role": "arena champion", "recruitable": false,
			"portrait_tint": Color(0.85, 0.60, 0.45),
			"schedule": {6: Vector2i(9, 1), 12: Vector2i(21, 1), 18: Vector2i(8, 17), 0: Vector2i(6, 5)},
			"dialogue_tree_id": "ma_marcus_default", "quest_hooks": ["ma_rigged_bouts"]},
		{"id": "ma_pit_master_grool", "name": "Pit Master Grool", "lineage": "Ferrusk", "role": "fight trainer", "recruitable": false,
			"portrait_tint": Color(0.70, 0.50, 0.40),
			"schedule": {6: Vector2i(7, 3), 12: Vector2i(9, 1), 18: Vector2i(22, 11), 0: Vector2i(7, 3)},
			"dialogue_tree_id": "ma_grool_default", "quest_hooks": []},
		{"id": "ma_betmaster_varek", "name": "Betmaster Varek", "lineage": "Gilded Human", "role": "bookie", "recruitable": false,
			"portrait_tint": Color(0.90, 0.75, 0.45),
			"schedule": {6: Vector2i(13, 10), 12: Vector2i(13, 10), 18: Vector2i(22, 11), 0: Vector2i(13, 10)},
			"dialogue_tree_id": "ma_varek_default", "quest_hooks": ["ma_rigged_bouts"]},
		{"id": "ma_trainer_axel", "name": "Trainer Axel", "lineage": "Boreal Human", "role": "combat trainer", "recruitable": false,
			"portrait_tint": Color(0.75, 0.65, 0.50),
			"schedule": {6: Vector2i(7, 3), 12: Vector2i(22, 9), 18: Vector2i(22, 11), 0: Vector2i(8, 17)},
			"dialogue_tree_id": "ma_axel_default", "quest_hooks": []},
		{"id": "ma_priestess_vona", "name": "Priestess Vona", "lineage": "Aetherian", "role": "combat priestess", "recruitable": false,
			"portrait_tint": Color(0.90, 0.85, 0.95),
			"schedule": {6: Vector2i(14, 7), 12: Vector2i(9, 1), 18: Vector2i(14, 7), 0: Vector2i(14, 7)},
			"dialogue_tree_id": "ma_vona_default", "quest_hooks": []},
		{"id": "ma_wounded_reto", "name": "Wounded Reto", "lineage": "Cragborn Human", "role": "retired gladiator", "recruitable": false,
			"portrait_tint": Color(0.65, 0.55, 0.45),
			"schedule": {6: Vector2i(8, 17), 12: Vector2i(22, 11), 18: Vector2i(22, 11), 0: Vector2i(8, 17)},
			"dialogue_tree_id": "ma_reto_default", "quest_hooks": []},
		{"id": "ma_crimson_madam", "name": "The Crimson Madam", "lineage": "Gilded Human", "role": "brothel keeper", "recruitable": false,
			"portrait_tint": Color(0.85, 0.40, 0.40),
			"schedule": {6: Vector2i(22, 11), 12: Vector2i(22, 11), 18: Vector2i(22, 11), 0: Vector2i(22, 11)},
			"dialogue_tree_id": "ma_madam_default", "quest_hooks": []},
		{"id": "ma_smith_felora", "name": "Master Smith Felora", "lineage": "Argent Dvarrim", "role": "weaponsmith", "recruitable": false,
			"portrait_tint": Color(0.80, 0.55, 0.35),
			"schedule": {6: Vector2i(24, 13), 12: Vector2i(24, 13), 18: Vector2i(22, 11), 0: Vector2i(24, 13)},
			"dialogue_tree_id": "ma_felora_default", "quest_hooks": []},
	],

	# ══════════════════════════════════════════════════════════════════════════
	# PEAKS OF ISOLATION — 5 NPCs
	# ══════════════════════════════════════════════════════════════════════════

	"Pharaoh's Den": [
		{"id": "pd_high_mummifier", "name": "High Mummifier Anubis", "lineage": "Ashenborn", "role": "chief embalmer", "recruitable": false,
			"portrait_tint": Color(0.55, 0.45, 0.40),
			"schedule": {6: Vector2i(10, 2), 12: Vector2i(14, 8), 18: Vector2i(9, 17), 0: Vector2i(10, 2)},
			"dialogue_tree_id": "pd_anubis_default", "quest_hooks": ["pd_cursed_tomb"]},
		{"id": "pd_tomb_reader_senet", "name": "Tomb Reader Senet", "lineage": "Arcanite Human", "role": "hieroglyph scholar", "recruitable": false,
			"portrait_tint": Color(0.75, 0.65, 0.45),
			"schedule": {6: Vector2i(6, 6), 12: Vector2i(14, 2), 18: Vector2i(22, 10), 0: Vector2i(9, 17)},
			"dialogue_tree_id": "pd_senet_default", "quest_hooks": ["pd_cursed_tomb"]},
		{"id": "pd_sand_walker_khetra", "name": "Sand-Walker Khetra", "lineage": "Boreal Human", "role": "desert guide", "recruitable": false,
			"portrait_tint": Color(0.80, 0.70, 0.50),
			"schedule": {6: Vector2i(19, 6), 12: Vector2i(22, 10), 18: Vector2i(22, 12), 0: Vector2i(9, 17)},
			"dialogue_tree_id": "pd_khetra_default", "quest_hooks": []},
		{"id": "pd_cursed_priest", "name": "Priest Ma'at", "lineage": "Ashenborn", "role": "curse-bound priest", "recruitable": false,
			"portrait_tint": Color(0.50, 0.40, 0.55),
			"schedule": {6: Vector2i(14, 8), 12: Vector2i(14, 8), 18: Vector2i(10, 2), 0: Vector2i(14, 8)},
			"dialogue_tree_id": "pd_maat_default", "quest_hooks": ["pd_cursed_tomb"]},
		{"id": "pd_merchant_rashid", "name": "Golden Merchant Rashid", "lineage": "Gilded Human", "role": "antiquities trader", "recruitable": false,
			"portrait_tint": Color(0.95, 0.80, 0.40),
			"schedule": {6: Vector2i(22, 10), 12: Vector2i(22, 10), 18: Vector2i(22, 12), 0: Vector2i(22, 10)},
			"dialogue_tree_id": "pd_rashid_default", "quest_hooks": []},
	],

	# ══════════════════════════════════════════════════════════════════════════
	# SHADOWS BENEATH — 5 per map
	# ══════════════════════════════════════════════════════════════════════════

	"The Darkness": [
		{"id": "td_mayor_hollowell", "name": "Mayor Hollowell", "lineage": "Boreal Human", "role": "haunted mayor", "recruitable": false,
			"portrait_tint": Color(0.50, 0.45, 0.55),
			"schedule": {6: Vector2i(5, 3), 12: Vector2i(5, 3), 18: Vector2i(24, 17), 0: Vector2i(4, 2)},
			"dialogue_tree_id": "td_hollowell_default", "quest_hooks": ["td_thing_in_the_dark"]},
		{"id": "td_lantern_mott", "name": "Lantern-Keeper Mott", "lineage": "Ferrusk", "role": "lamplighter", "recruitable": false,
			"portrait_tint": Color(0.75, 0.60, 0.30),
			"schedule": {6: Vector2i(13, 7), 12: Vector2i(6, 12), 18: Vector2i(13, 7), 0: Vector2i(24, 17)},
			"dialogue_tree_id": "td_mott_default", "quest_hooks": []},
		{"id": "td_widow_black", "name": "Widow Black", "lineage": "Gravetouched", "role": "bereaved widow", "recruitable": false,
			"portrait_tint": Color(0.35, 0.30, 0.45),
			"schedule": {6: Vector2i(9, 5), 12: Vector2i(9, 5), 18: Vector2i(24, 17), 0: Vector2i(9, 5)},
			"dialogue_tree_id": "td_black_default", "quest_hooks": ["td_thing_in_the_dark"]},
		{"id": "td_shopkeeper", "name": "The Shopkeeper", "lineage": "Duskling", "role": "unnamed merchant", "recruitable": false,
			"portrait_tint": Color(0.40, 0.40, 0.50),
			"schedule": {6: Vector2i(6, 12), 12: Vector2i(6, 12), 18: Vector2i(20, 9), 0: Vector2i(24, 17)},
			"dialogue_tree_id": "td_shop_default", "quest_hooks": []},
		{"id": "td_preacher_blight", "name": "Preacher Blight", "lineage": "Arcanite Human", "role": "doomsday preacher", "recruitable": false,
			"portrait_tint": Color(0.55, 0.40, 0.45),
			"schedule": {6: Vector2i(9, 5), 12: Vector2i(5, 3), 18: Vector2i(9, 5), 0: Vector2i(13, 7)},
			"dialogue_tree_id": "td_blight_default", "quest_hooks": []},
	],

	"House of Arachana": [
		{"id": "ha_matriarch", "name": "Web-Weaver Matriarch", "lineage": "Duskling", "role": "brood matriarch", "recruitable": false,
			"portrait_tint": Color(0.35, 0.30, 0.50),
			"schedule": {6: Vector2i(7, 1), 12: Vector2i(8, 8), 18: Vector2i(9, 16), 0: Vector2i(7, 1)},
			"dialogue_tree_id": "ha_matriarch_default", "quest_hooks": ["ha_silk_tax"]},
		{"id": "ha_silk_kess", "name": "Silk Merchant Kess", "lineage": "Nimbari", "role": "silk trader", "recruitable": false,
			"portrait_tint": Color(0.75, 0.65, 0.40),
			"schedule": {6: Vector2i(20, 8), 12: Vector2i(20, 8), 18: Vector2i(22, 13), 0: Vector2i(9, 16)},
			"dialogue_tree_id": "ha_kess_default", "quest_hooks": []},
		{"id": "ha_venom_orin", "name": "Venom-Brewer Orin", "lineage": "Bramblekin", "role": "apothecary", "recruitable": false,
			"portrait_tint": Color(0.55, 0.70, 0.45),
			"schedule": {6: Vector2i(22, 18), 12: Vector2i(22, 18), 18: Vector2i(22, 13), 0: Vector2i(22, 18)},
			"dialogue_tree_id": "ha_orin_default", "quest_hooks": []},
		{"id": "ha_priestess", "name": "Spider Priestess", "lineage": "Fae-Touched Human", "role": "spider priestess", "recruitable": false,
			"portrait_tint": Color(0.50, 0.45, 0.65),
			"schedule": {6: Vector2i(7, 3), 12: Vector2i(8, 8), 18: Vector2i(7, 3), 0: Vector2i(8, 8)},
			"dialogue_tree_id": "ha_priestess_default", "quest_hooks": ["ha_silk_tax"]},
		{"id": "ha_brood_trask", "name": "Brood-Tender Trask", "lineage": "Ferrusk", "role": "brood tender", "recruitable": false,
			"portrait_tint": Color(0.55, 0.45, 0.35),
			"schedule": {6: Vector2i(18, 2), 12: Vector2i(18, 2), 18: Vector2i(9, 16), 0: Vector2i(18, 2)},
			"dialogue_tree_id": "ha_trask_default", "quest_hooks": []},
	],

	"Crypt at End of Valley": [
		{"id": "ce_gravekeeper_mortis", "name": "Gravekeeper Mortis", "lineage": "Gravetouched", "role": "chief gravekeeper", "recruitable": false,
			"portrait_tint": Color(0.45, 0.40, 0.55),
			"schedule": {6: Vector2i(11, 5), 12: Vector2i(15, 20), 18: Vector2i(22, 7), 0: Vector2i(11, 5)},
			"dialogue_tree_id": "ce_mortis_default", "quest_hooks": ["ce_stolen_urn"]},
		{"id": "ce_priestess_lara", "name": "Priestess Lara", "lineage": "Aetherian", "role": "mourning priestess", "recruitable": false,
			"portrait_tint": Color(0.85, 0.85, 0.95),
			"schedule": {6: Vector2i(3, 3), 12: Vector2i(11, 5), 18: Vector2i(22, 7), 0: Vector2i(11, 5)},
			"dialogue_tree_id": "ce_lara_default", "quest_hooks": []},
		{"id": "ce_guard_tark", "name": "Sepulcher Guard Tark", "lineage": "Cragborn Human", "role": "crypt guard", "recruitable": false,
			"portrait_tint": Color(0.55, 0.60, 0.65),
			"schedule": {6: Vector2i(2, 1), 12: Vector2i(22, 1), 18: Vector2i(5, 9), 0: Vector2i(22, 1)},
			"dialogue_tree_id": "ce_tark_default", "quest_hooks": ["ce_stolen_urn"]},
		{"id": "ce_carver_oswin", "name": "Bone-Carver Oswin", "lineage": "Argent Dvarrim", "role": "memorial carver", "recruitable": false,
			"portrait_tint": Color(0.70, 0.60, 0.45),
			"schedule": {6: Vector2i(25, 11), 12: Vector2i(25, 11), 18: Vector2i(5, 9), 0: Vector2i(25, 11)},
			"dialogue_tree_id": "ce_oswin_default", "quest_hooks": []},
		{"id": "ce_monk_silas", "name": "Vigil Monk Silas", "lineage": "Arcanite Human", "role": "vigil monk", "recruitable": false,
			"portrait_tint": Color(0.60, 0.55, 0.70),
			"schedule": {6: Vector2i(22, 7), 12: Vector2i(22, 7), 18: Vector2i(22, 7), 0: Vector2i(22, 7)},
			"dialogue_tree_id": "ce_silas_default", "quest_hooks": []},
	],

	"Spindle York's Schism": [
		{"id": "sy_guide_tess", "name": "Canyon Guide Tess", "lineage": "Nimbari", "role": "chasm guide", "recruitable": false,
			"portrait_tint": Color(0.70, 0.65, 0.45),
			"schedule": {6: Vector2i(4, 5), 12: Vector2i(5, 5), 18: Vector2i(22, 8), 0: Vector2i(4, 5)},
			"dialogue_tree_id": "sy_tess_default", "quest_hooks": ["sy_missing_climbers"]},
		{"id": "sy_hermit", "name": "The Void-Touched Hermit", "lineage": "Fae-Touched Human", "role": "hermit", "recruitable": false,
			"portrait_tint": Color(0.40, 0.35, 0.55),
			"schedule": {6: Vector2i(15, 20), 12: Vector2i(15, 20), 18: Vector2i(15, 20), 0: Vector2i(15, 20)},
			"dialogue_tree_id": "sy_hermit_default", "quest_hooks": ["sy_missing_climbers"]},
		{"id": "sy_priest_vashnar", "name": "Cult Priest Vashnar", "lineage": "Duskling", "role": "void cultist", "recruitable": false,
			"portrait_tint": Color(0.35, 0.30, 0.50),
			"schedule": {6: Vector2i(8, 9), 12: Vector2i(8, 9), 18: Vector2i(8, 9), 0: Vector2i(15, 20)},
			"dialogue_tree_id": "sy_vashnar_default", "quest_hooks": []},
		{"id": "sy_miner_orik", "name": "Abyss Miner Orik", "lineage": "Argent Dvarrim", "role": "deep miner", "recruitable": false,
			"portrait_tint": Color(0.60, 0.45, 0.30),
			"schedule": {6: Vector2i(3, 2), 12: Vector2i(22, 2), 18: Vector2i(8, 9), 0: Vector2i(8, 9)},
			"dialogue_tree_id": "sy_orik_default", "quest_hooks": []},
		{"id": "sy_watcher_yulia", "name": "Schism Watcher Yulia", "lineage": "Boreal Human", "role": "schism observer", "recruitable": false,
			"portrait_tint": Color(0.65, 0.60, 0.70),
			"schedule": {6: Vector2i(1, 0), 12: Vector2i(27, 0), 18: Vector2i(15, 20), 0: Vector2i(1, 0)},
			"dialogue_tree_id": "sy_yulia_default", "quest_hooks": []},
	],

	# ══════════════════════════════════════════════════════════════════════════
	# GLASS PASSAGE — 5 per map (remote-sparse)
	# ══════════════════════════════════════════════════════════════════════════

	"Argent Hall": [
		{"id": "ah_carver_ander", "name": "Glacier-Carver Ander", "lineage": "Frostborn", "role": "ice sculptor", "recruitable": false,
			"portrait_tint": Color(0.75, 0.85, 0.95),
			"schedule": {6: Vector2i(4, 2), 12: Vector2i(6, 5), 18: Vector2i(22, 8), 0: Vector2i(4, 2)},
			"dialogue_tree_id": "ah_ander_default", "quest_hooks": ["ah_frozen_stranger"]},
		{"id": "ah_priest_tova", "name": "Frost-Priest Tova", "lineage": "Aetherian", "role": "frost priest", "recruitable": false,
			"portrait_tint": Color(0.85, 0.90, 1.0),
			"schedule": {6: Vector2i(12, 5), 12: Vector2i(15, 20), 18: Vector2i(12, 5), 0: Vector2i(12, 5)},
			"dialogue_tree_id": "ah_tova_default", "quest_hooks": []},
		{"id": "ah_voss", "name": "Crystal Master Voss", "lineage": "Argent Dvarrim", "role": "crystalwright", "recruitable": false,
			"portrait_tint": Color(0.70, 0.60, 0.40),
			"schedule": {6: Vector2i(25, 0), 12: Vector2i(21, 2), 18: Vector2i(25, 12), 0: Vector2i(25, 0)},
			"dialogue_tree_id": "ah_voss_default", "quest_hooks": []},
		{"id": "ah_scout_hark", "name": "Tundra Scout Hark", "lineage": "Cragborn Human", "role": "tundra scout", "recruitable": false,
			"portrait_tint": Color(0.65, 0.70, 0.75),
			"schedule": {6: Vector2i(1, 0), 12: Vector2i(9, 9), 18: Vector2i(22, 8), 0: Vector2i(9, 9)},
			"dialogue_tree_id": "ah_hark_default", "quest_hooks": ["ah_frozen_stranger"]},
		{"id": "ah_edda", "name": "Icecrafter Edda", "lineage": "Frostborn", "role": "icecrafter", "recruitable": false,
			"portrait_tint": Color(0.80, 0.88, 0.98),
			"schedule": {6: Vector2i(25, 12), 12: Vector2i(6, 5), 18: Vector2i(9, 9), 0: Vector2i(25, 12)},
			"dialogue_tree_id": "ah_edda_default", "quest_hooks": []},
	],

	"Sacral Separation": [
		{"id": "ss_monk_keen", "name": "Monk Keen", "lineage": "Arcanite Human", "role": "contemplative monk", "recruitable": false,
			"portrait_tint": Color(0.75, 0.70, 0.60),
			"schedule": {6: Vector2i(17, 5), 12: Vector2i(9, 10), 18: Vector2i(17, 5), 0: Vector2i(17, 5)},
			"dialogue_tree_id": "ss_keen_default", "quest_hooks": ["ss_silent_order"]},
		{"id": "ss_guide_saber", "name": "Desert Guide Saber", "lineage": "Boreal Human", "role": "desert guide", "recruitable": false,
			"portrait_tint": Color(0.80, 0.70, 0.50),
			"schedule": {6: Vector2i(4, 2), 12: Vector2i(21, 2), 18: Vector2i(22, 8), 0: Vector2i(22, 8)},
			"dialogue_tree_id": "ss_saber_default", "quest_hooks": []},
		{"id": "ss_pilgrim_vassal", "name": "Pilgrim Vassal", "lineage": "Gilded Human", "role": "devoted pilgrim", "recruitable": false,
			"portrait_tint": Color(0.90, 0.85, 0.70),
			"schedule": {6: Vector2i(2, 0), 12: Vector2i(15, 20), 18: Vector2i(22, 8), 0: Vector2i(17, 5)},
			"dialogue_tree_id": "ss_vassal_default", "quest_hooks": []},
		{"id": "ss_watcher_ellar", "name": "Obelisk Watcher Ellar", "lineage": "Aetherian", "role": "obelisk scholar", "recruitable": false,
			"portrait_tint": Color(0.85, 0.90, 1.0),
			"schedule": {6: Vector2i(2, 0), 12: Vector2i(23, 0), 18: Vector2i(15, 20), 0: Vector2i(2, 0)},
			"dialogue_tree_id": "ss_ellar_default", "quest_hooks": ["ss_silent_order"]},
		{"id": "ss_thada", "name": "Holy Forger Thada", "lineage": "Argent Dvarrim", "role": "sacred smith", "recruitable": false,
			"portrait_tint": Color(0.80, 0.65, 0.35),
			"schedule": {6: Vector2i(26, 11), 12: Vector2i(26, 11), 18: Vector2i(22, 8), 0: Vector2i(26, 11)},
			"dialogue_tree_id": "ss_thada_default", "quest_hooks": []},
	],

	# ══════════════════════════════════════════════════════════════════════════
	# THE ISLES — 6 per map
	# ══════════════════════════════════════════════════════════════════════════

	"Depths of Denorim": [
		{"id": "dd_prince_mirelle", "name": "Sea Prince Mirelle", "lineage": "Fathomari", "role": "heir to the coral throne", "recruitable": false,
			"portrait_tint": Color(0.40, 0.75, 0.85),
			"schedule": {6: Vector2i(2, 0), 12: Vector2i(23, 0), 18: Vector2i(17, 5), 0: Vector2i(2, 0)},
			"dialogue_tree_id": "dd_mirelle_default", "quest_hooks": ["dd_kraken_sighting"]},
		{"id": "dd_nept", "name": "Coral Master Nept", "lineage": "Fathomari", "role": "coral architect", "recruitable": false,
			"portrait_tint": Color(0.85, 0.50, 0.60),
			"schedule": {6: Vector2i(23, 0), 12: Vector2i(23, 0), 18: Vector2i(26, 11), 0: Vector2i(26, 11)},
			"dialogue_tree_id": "dd_nept_default", "quest_hooks": []},
		{"id": "dd_dorsal", "name": "Kelp-Farmer Dorsal", "lineage": "Fathomari", "role": "kelp farmer", "recruitable": false,
			"portrait_tint": Color(0.55, 0.75, 0.50),
			"schedule": {6: Vector2i(2, 2), 12: Vector2i(2, 2), 18: Vector2i(22, 8), 0: Vector2i(9, 10)},
			"dialogue_tree_id": "dd_dorsal_default", "quest_hooks": []},
		{"id": "dd_urvay", "name": "Brine-Trader Urvay", "lineage": "Nimbari", "role": "salt merchant", "recruitable": false,
			"portrait_tint": Color(0.75, 0.70, 0.55),
			"schedule": {6: Vector2i(7, 5), 12: Vector2i(7, 5), 18: Vector2i(9, 10), 0: Vector2i(22, 8)},
			"dialogue_tree_id": "dd_urvay_default", "quest_hooks": []},
		{"id": "dd_alleria", "name": "Tide-Singer Alleria", "lineage": "Fae-Touched Human", "role": "tide singer", "recruitable": false,
			"portrait_tint": Color(0.70, 0.85, 0.95),
			"schedule": {6: Vector2i(17, 5), 12: Vector2i(15, 20), 18: Vector2i(9, 10), 0: Vector2i(17, 5)},
			"dialogue_tree_id": "dd_alleria_default", "quest_hooks": ["dd_kraken_sighting"]},
		{"id": "dd_calvus", "name": "Sunken Guard Calvus", "lineage": "Cragborn Human", "role": "palace guard", "recruitable": false,
			"portrait_tint": Color(0.55, 0.65, 0.75),
			"schedule": {6: Vector2i(2, 0), 12: Vector2i(15, 20), 18: Vector2i(21, 2), 0: Vector2i(2, 0)},
			"dialogue_tree_id": "dd_calvus_default", "quest_hooks": []},
	],

	"Corrupted Marshes": [
		{"id": "cm_vortimer", "name": "Lich-Lord Vortimer", "lineage": "Gravetouched", "role": "lich lord", "recruitable": false,
			"portrait_tint": Color(0.40, 0.45, 0.55),
			"schedule": {6: Vector2i(17, 2), 12: Vector2i(17, 2), 18: Vector2i(15, 20), 0: Vector2i(17, 2)},
			"dialogue_tree_id": "cm_vortimer_default", "quest_hooks": ["cm_lich_bargain"]},
		{"id": "cm_grellith", "name": "Swamp Witch Grellith", "lineage": "Bramblekin", "role": "swamp witch", "recruitable": false,
			"portrait_tint": Color(0.45, 0.55, 0.35),
			"schedule": {6: Vector2i(4, 1), 12: Vector2i(4, 1), 18: Vector2i(3, 8), 0: Vector2i(8, 5)},
			"dialogue_tree_id": "cm_grellith_default", "quest_hooks": []},
		{"id": "cm_karsk", "name": "Bone Priest Karsk", "lineage": "Gravetouched", "role": "bone priest", "recruitable": false,
			"portrait_tint": Color(0.55, 0.50, 0.60),
			"schedule": {6: Vector2i(25, 1), 12: Vector2i(25, 1), 18: Vector2i(15, 20), 0: Vector2i(25, 1)},
			"dialogue_tree_id": "cm_karsk_default", "quest_hooks": ["cm_lich_bargain"]},
		{"id": "cm_rotvel", "name": "Marsh Merchant Rotvel", "lineage": "Ferrusk", "role": "carrion trader", "recruitable": false,
			"portrait_tint": Color(0.60, 0.50, 0.40),
			"schedule": {6: Vector2i(8, 5), 12: Vector2i(8, 5), 18: Vector2i(3, 8), 0: Vector2i(8, 5)},
			"dialogue_tree_id": "cm_rotvel_default", "quest_hooks": []},
		{"id": "cm_moll", "name": "Keeper of Graves Moll", "lineage": "Arcanite Human", "role": "grave warden", "recruitable": false,
			"portrait_tint": Color(0.65, 0.60, 0.75),
			"schedule": {6: Vector2i(20, 10), 12: Vector2i(20, 10), 18: Vector2i(3, 8), 0: Vector2i(20, 10)},
			"dialogue_tree_id": "cm_moll_default", "quest_hooks": []},
		{"id": "cm_brem", "name": "Cursed Hunter Brem", "lineage": "Ashenborn", "role": "cursed hunter", "recruitable": false,
			"portrait_tint": Color(0.50, 0.45, 0.55),
			"schedule": {6: Vector2i(12, 4), 12: Vector2i(12, 4), 18: Vector2i(26, 12), 0: Vector2i(3, 8)},
			"dialogue_tree_id": "cm_brem_default", "quest_hooks": []},
	],

	"Gloamfen Hollow": [
		{"id": "gh_viscer", "name": "Cathedral Keeper Viscer", "lineage": "Ashenborn", "role": "cathedral keeper", "recruitable": false,
			"portrait_tint": Color(0.50, 0.40, 0.50),
			"schedule": {6: Vector2i(2, 0), 12: Vector2i(2, 0), 18: Vector2i(15, 20), 0: Vector2i(2, 0)},
			"dialogue_tree_id": "gh_viscer_default", "quest_hooks": ["gh_living_cathedral"]},
		{"id": "gh_pith", "name": "Organ-Tender Pith", "lineage": "Gravetouched", "role": "organ tender", "recruitable": false,
			"portrait_tint": Color(0.55, 0.50, 0.60),
			"schedule": {6: Vector2i(2, 2), 12: Vector2i(2, 2), 18: Vector2i(9, 10), 0: Vector2i(2, 2)},
			"dialogue_tree_id": "gh_pith_default", "quest_hooks": []},
		{"id": "gh_maros", "name": "Bile Brewer Maros", "lineage": "Bramblekin", "role": "bile brewer", "recruitable": false,
			"portrait_tint": Color(0.50, 0.60, 0.40),
			"schedule": {6: Vector2i(21, 2), 12: Vector2i(21, 2), 18: Vector2i(9, 10), 0: Vector2i(9, 10)},
			"dialogue_tree_id": "gh_maros_default", "quest_hooks": []},
		{"id": "gh_kish", "name": "Decay Priest Kish", "lineage": "Gravetouched", "role": "decay priest", "recruitable": false,
			"portrait_tint": Color(0.45, 0.45, 0.55),
			"schedule": {6: Vector2i(17, 5), 12: Vector2i(15, 20), 18: Vector2i(17, 5), 0: Vector2i(17, 5)},
			"dialogue_tree_id": "gh_kish_default", "quest_hooks": ["gh_living_cathedral"]},
		{"id": "gh_thul", "name": "Bone-Merchant Thul", "lineage": "Ferrusk", "role": "bone merchant", "recruitable": false,
			"portrait_tint": Color(0.55, 0.48, 0.42),
			"schedule": {6: Vector2i(7, 5), 12: Vector2i(7, 5), 18: Vector2i(9, 10), 0: Vector2i(7, 5)},
			"dialogue_tree_id": "gh_thul_default", "quest_hooks": []},
		{"id": "gh_ylba", "name": "Flesh-Weaver Ylba", "lineage": "Fae-Touched Human", "role": "flesh weaver", "recruitable": false,
			"portrait_tint": Color(0.75, 0.55, 0.60),
			"schedule": {6: Vector2i(26, 11), 12: Vector2i(26, 11), 18: Vector2i(22, 8), 0: Vector2i(26, 11)},
			"dialogue_tree_id": "gh_ylba_default", "quest_hooks": []},
	],

	"Moroboros": [
		{"id": "mb_paradox", "name": "Timekeeper Paradox", "lineage": "Fae-Touched Human", "role": "timekeeper", "recruitable": false,
			"portrait_tint": Color(0.65, 0.55, 0.85),
			"schedule": {6: Vector2i(23, 0), 12: Vector2i(15, 20), 18: Vector2i(2, 0), 0: Vector2i(17, 5)},
			"dialogue_tree_id": "mb_paradox_default", "quest_hooks": ["mb_hour_that_shouldnt_exist"]},
		{"id": "mb_null", "name": "Dream Shepherd Null", "lineage": "Aetherian", "role": "dream shepherd", "recruitable": false,
			"portrait_tint": Color(0.55, 0.70, 0.95),
			"schedule": {6: Vector2i(2, 0), 12: Vector2i(2, 2), 18: Vector2i(15, 20), 0: Vector2i(2, 0)},
			"dialogue_tree_id": "mb_null_default", "quest_hooks": []},
		{"id": "mb_six", "name": "Reality Weaver Six", "lineage": "Glimmerfolk", "role": "reality weaver", "recruitable": false,
			"portrait_tint": Color(0.80, 0.85, 1.0),
			"schedule": {6: Vector2i(17, 5), 12: Vector2i(21, 2), 18: Vector2i(17, 5), 0: Vector2i(7, 5)},
			"dialogue_tree_id": "mb_six_default", "quest_hooks": []},
		{"id": "mb_smith", "name": "The Impossible Smith", "lineage": "Argent Dvarrim", "role": "impossible smith", "recruitable": false,
			"portrait_tint": Color(0.70, 0.60, 0.45),
			"schedule": {6: Vector2i(26, 11), 12: Vector2i(26, 11), 18: Vector2i(9, 10), 0: Vector2i(26, 11)},
			"dialogue_tree_id": "mb_smith_default", "quest_hooks": []},
		{"id": "mb_surreal", "name": "The Surreal One", "lineage": "Duskling", "role": "surreal wanderer", "recruitable": false,
			"portrait_tint": Color(0.50, 0.45, 0.70),
			"schedule": {6: Vector2i(9, 10), 12: Vector2i(15, 20), 18: Vector2i(22, 8), 0: Vector2i(2, 2)},
			"dialogue_tree_id": "mb_surreal_default", "quest_hooks": ["mb_hour_that_shouldnt_exist"]},
		{"id": "mb_zera", "name": "Future-Echo Zera", "lineage": "Fae-Touched Human", "role": "future-echo", "recruitable": false,
			"portrait_tint": Color(0.80, 0.70, 0.95),
			"schedule": {6: Vector2i(7, 5), 12: Vector2i(9, 10), 18: Vector2i(17, 5), 0: Vector2i(7, 5)},
			"dialogue_tree_id": "mb_zera_default", "quest_hooks": []},
	],

	# ══════════════════════════════════════════════════════════════════════════
	# TITAN'S LAMENT — 6 per map
	# ══════════════════════════════════════════════════════════════════════════

	"Vulcan Valley": [
		{"id": "vv_pyrus", "name": "Forgemaster Pyrus", "lineage": "Cindervolk", "role": "forgemaster", "recruitable": false,
			"portrait_tint": Color(0.90, 0.45, 0.30),
			"schedule": {6: Vector2i(24, 8), 12: Vector2i(11, 4), 18: Vector2i(14, 19), 0: Vector2i(24, 8)},
			"dialogue_tree_id": "vv_pyrus_default", "quest_hooks": ["vv_titan_heart"]},
		{"id": "vv_mira", "name": "Lava-Wraith Mira", "lineage": "Fae-Touched Human", "role": "lava wraith", "recruitable": false,
			"portrait_tint": Color(0.90, 0.55, 0.40),
			"schedule": {6: Vector2i(15, 10), 12: Vector2i(13, 8), 18: Vector2i(15, 10), 0: Vector2i(15, 10)},
			"dialogue_tree_id": "vv_mira_default", "quest_hooks": []},
		{"id": "vv_rhael", "name": "Ember Scout Rhael", "lineage": "Cragborn Human", "role": "ember scout", "recruitable": false,
			"portrait_tint": Color(0.75, 0.55, 0.40),
			"schedule": {6: Vector2i(6, 5), 12: Vector2i(4, 2), 18: Vector2i(8, 13), 0: Vector2i(14, 19)},
			"dialogue_tree_id": "vv_rhael_default", "quest_hooks": []},
		{"id": "vv_trader", "name": "Ember Trader Solne", "lineage": "Gilded Human", "role": "ember trader", "recruitable": false,
			"portrait_tint": Color(0.95, 0.75, 0.50),
			"schedule": {6: Vector2i(8, 13), 12: Vector2i(8, 13), 18: Vector2i(14, 19), 0: Vector2i(8, 13)},
			"dialogue_tree_id": "vv_solne_default", "quest_hooks": []},
		{"id": "vv_priest", "name": "Priest Ignus", "lineage": "Aetherian", "role": "volcano priest", "recruitable": false,
			"portrait_tint": Color(0.95, 0.85, 0.75),
			"schedule": {6: Vector2i(13, 8), 12: Vector2i(13, 8), 18: Vector2i(15, 10), 0: Vector2i(13, 8)},
			"dialogue_tree_id": "vv_ignus_default", "quest_hooks": ["vv_titan_heart"]},
		{"id": "vv_vulk", "name": "Firesmith Vulk", "lineage": "Cindervolk", "role": "firesmith apprentice", "recruitable": false,
			"portrait_tint": Color(0.85, 0.40, 0.30),
			"schedule": {6: Vector2i(24, 8), 12: Vector2i(24, 8), 18: Vector2i(14, 19), 0: Vector2i(24, 8)},
			"dialogue_tree_id": "vv_vulk_default", "quest_hooks": []},
	],

	"Infernal Machine": [
		{"id": "im_damn", "name": "Overseer Damn", "lineage": "Cindervolk", "role": "infernal overseer", "recruitable": false,
			"portrait_tint": Color(0.80, 0.30, 0.25),
			"schedule": {6: Vector2i(17, 5), 12: Vector2i(23, 0), 18: Vector2i(15, 20), 0: Vector2i(17, 5)},
			"dialogue_tree_id": "im_damn_default", "quest_hooks": ["im_contract_loophole"]},
		{"id": "im_riva", "name": "Soul-Collector Riva", "lineage": "Duskling", "role": "contract agent", "recruitable": false,
			"portrait_tint": Color(0.35, 0.30, 0.45),
			"schedule": {6: Vector2i(23, 0), 12: Vector2i(7, 5), 18: Vector2i(22, 8), 0: Vector2i(7, 5)},
			"dialogue_tree_id": "im_riva_default", "quest_hooks": ["im_contract_loophole"]},
		{"id": "im_kolk", "name": "Brass-Warden Kolk", "lineage": "Cragborn Human", "role": "brass warden", "recruitable": false,
			"portrait_tint": Color(0.60, 0.55, 0.35),
			"schedule": {6: Vector2i(2, 2), 12: Vector2i(15, 20), 18: Vector2i(22, 8), 0: Vector2i(2, 2)},
			"dialogue_tree_id": "im_kolk_default", "quest_hooks": []},
		{"id": "im_warden", "name": "Damnation Warden Ven", "lineage": "Cindervolk", "role": "damnation warden", "recruitable": false,
			"portrait_tint": Color(0.85, 0.45, 0.30),
			"schedule": {6: Vector2i(21, 2), 12: Vector2i(21, 2), 18: Vector2i(9, 10), 0: Vector2i(21, 2)},
			"dialogue_tree_id": "im_ven_default", "quest_hooks": []},
		{"id": "im_oleaf", "name": "Sulfur Brewer Oleaf", "lineage": "Bramblekin", "role": "sulfur brewer", "recruitable": false,
			"portrait_tint": Color(0.70, 0.65, 0.30),
			"schedule": {6: Vector2i(9, 10), 12: Vector2i(9, 10), 18: Vector2i(9, 10), 0: Vector2i(9, 10)},
			"dialogue_tree_id": "im_oleaf_default", "quest_hooks": []},
		{"id": "im_marrok", "name": "Infernal Smith Marrok", "lineage": "Argent Dvarrim", "role": "infernal smith", "recruitable": false,
			"portrait_tint": Color(0.75, 0.45, 0.30),
			"schedule": {6: Vector2i(26, 11), 12: Vector2i(26, 11), 18: Vector2i(9, 10), 0: Vector2i(26, 11)},
			"dialogue_tree_id": "im_marrok_default", "quest_hooks": []},
	],

	# ══════════════════════════════════════════════════════════════════════════
	# ASTRAL TEAR — 5 per map
	# ══════════════════════════════════════════════════════════════════════════

	"Arcane Collapse": [
		{"id": "ac_vess", "name": "Reality Surgeon Vess", "lineage": "Arcanite Human", "role": "reality surgeon", "recruitable": false,
			"portrait_tint": Color(0.70, 0.60, 0.90),
			"schedule": {6: Vector2i(10, 5), 12: Vector2i(5, 3), 18: Vector2i(13, 7), 0: Vector2i(10, 5)},
			"dialogue_tree_id": "ac_vess_default", "quest_hooks": ["ac_reality_tear"]},
		{"id": "ac_telm", "name": "Mana-Mad Priest Telm", "lineage": "Fae-Touched Human", "role": "mana-mad priest", "recruitable": false,
			"portrait_tint": Color(0.80, 0.65, 0.95),
			"schedule": {6: Vector2i(3, 5), 12: Vector2i(3, 5), 18: Vector2i(24, 17), 0: Vector2i(3, 5)},
			"dialogue_tree_id": "ac_telm_default", "quest_hooks": []},
		{"id": "ac_keeper", "name": "Tower Keeper Aeol", "lineage": "Aetherian", "role": "fractured tower keeper", "recruitable": false,
			"portrait_tint": Color(0.90, 0.90, 1.0),
			"schedule": {6: Vector2i(4, 1), 12: Vector2i(9, 1), 18: Vector2i(18, 1), 0: Vector2i(4, 1)},
			"dialogue_tree_id": "ac_aeol_default", "quest_hooks": ["ac_reality_tear"]},
		{"id": "ac_elyth", "name": "Spell-Trader Elyth", "lineage": "Elf", "role": "spell trader", "recruitable": false,
			"portrait_tint": Color(0.65, 0.80, 0.75),
			"schedule": {6: Vector2i(6, 12), 12: Vector2i(6, 12), 18: Vector2i(24, 17), 0: Vector2i(6, 12)},
			"dialogue_tree_id": "ac_elyth_default", "quest_hooks": []},
		{"id": "ac_ethereal_smith", "name": "Ethereal Smith Orvan", "lineage": "Argent Dvarrim", "role": "ethereal smith", "recruitable": false,
			"portrait_tint": Color(0.70, 0.70, 0.85),
			"schedule": {6: Vector2i(20, 9), 12: Vector2i(20, 9), 18: Vector2i(24, 17), 0: Vector2i(20, 9)},
			"dialogue_tree_id": "ac_orvan_default", "quest_hooks": []},
	],

	"L.I.T.O.": [
		{"id": "lito_thought", "name": "Council Elder Thought", "lineage": "Aetherian", "role": "council elder", "recruitable": false,
			"portrait_tint": Color(0.85, 0.90, 1.0),
			"schedule": {6: Vector2i(13, 8), 12: Vector2i(15, 10), 18: Vector2i(14, 19), 0: Vector2i(13, 8)},
			"dialogue_tree_id": "lito_thought_default", "quest_hooks": ["lito_missing_mind"]},
		{"id": "lito_zetha", "name": "Mind-Walker Zetha", "lineage": "Fae-Touched Human", "role": "mind-walker", "recruitable": false,
			"portrait_tint": Color(0.65, 0.80, 0.95),
			"schedule": {6: Vector2i(4, 2), 12: Vector2i(13, 2), 18: Vector2i(2, 8), 0: Vector2i(14, 19)},
			"dialogue_tree_id": "lito_zetha_default", "quest_hooks": []},
		{"id": "lito_astral", "name": "Dream Shepherd Astral", "lineage": "Glimmerfolk", "role": "dream shepherd", "recruitable": false,
			"portrait_tint": Color(0.75, 0.85, 1.0),
			"schedule": {6: Vector2i(6, 6), 12: Vector2i(2, 8), 18: Vector2i(14, 19), 0: Vector2i(6, 6)},
			"dialogue_tree_id": "lito_astral_default", "quest_hooks": []},
		{"id": "lito_ironthought", "name": "Mindsmith Iron-Thought", "lineage": "Argent Dvarrim", "role": "mindsmith", "recruitable": false,
			"portrait_tint": Color(0.70, 0.65, 0.85),
			"schedule": {6: Vector2i(24, 8), 12: Vector2i(24, 8), 18: Vector2i(14, 19), 0: Vector2i(24, 8)},
			"dialogue_tree_id": "lito_smith_default", "quest_hooks": []},
		{"id": "lito_voi", "name": "Consciousness Trader Voi", "lineage": "Aetherian", "role": "consciousness trader", "recruitable": false,
			"portrait_tint": Color(0.95, 0.95, 1.0),
			"schedule": {6: Vector2i(8, 13), 12: Vector2i(8, 13), 18: Vector2i(14, 19), 0: Vector2i(20, 2)},
			"dialogue_tree_id": "lito_voi_default", "quest_hooks": ["lito_missing_mind"]},
	],

	"Land of Tomorrow": [
		{"id": "lot_orbit", "name": "Commander Orbit", "lineage": "Boreal Human", "role": "station commander", "recruitable": false,
			"portrait_tint": Color(0.70, 0.80, 0.90),
			"schedule": {6: Vector2i(4, 3), 12: Vector2i(5, 3), 18: Vector2i(24, 17), 0: Vector2i(4, 3)},
			"dialogue_tree_id": "lot_orbit_default", "quest_hooks": ["lot_airlock_incident"]},
		{"id": "lot_freya", "name": "Cryo-Tech Freya", "lineage": "Arcanite Human", "role": "cryo-technician", "recruitable": false,
			"portrait_tint": Color(0.70, 0.85, 0.95),
			"schedule": {6: Vector2i(18, 2), 12: Vector2i(13, 7), 18: Vector2i(24, 17), 0: Vector2i(18, 2)},
			"dialogue_tree_id": "lot_freya_default", "quest_hooks": ["lot_airlock_incident"]},
		{"id": "lot_peel", "name": "Stellar Chef Peel", "lineage": "Ferrusk", "role": "station cook", "recruitable": false,
			"portrait_tint": Color(0.85, 0.75, 0.55),
			"schedule": {6: Vector2i(24, 17), 12: Vector2i(24, 17), 18: Vector2i(24, 17), 0: Vector2i(24, 17)},
			"dialogue_tree_id": "lot_peel_default", "quest_hooks": []},
		{"id": "lot_vrix", "name": "Plasma Engineer Vrix", "lineage": "Nimbari", "role": "plasma engineer", "recruitable": false,
			"portrait_tint": Color(0.85, 0.75, 0.40),
			"schedule": {6: Vector2i(20, 9), 12: Vector2i(9, 5), 18: Vector2i(24, 17), 0: Vector2i(20, 9)},
			"dialogue_tree_id": "lot_vrix_default", "quest_hooks": []},
		{"id": "lot_kelvyn", "name": "Airlock Officer Kelvyn", "lineage": "Cragborn Human", "role": "airlock officer", "recruitable": false,
			"portrait_tint": Color(0.60, 0.70, 0.80),
			"schedule": {6: Vector2i(9, 1), 12: Vector2i(9, 1), 18: Vector2i(9, 1), 0: Vector2i(9, 1)},
			"dialogue_tree_id": "lot_kelvyn_default", "quest_hooks": ["lot_airlock_incident"]},
	],

	# ══════════════════════════════════════════════════════════════════════════
	# TERMINUS VOLARUS — 8 city, 7 sacrament
	# ══════════════════════════════════════════════════════════════════════════

	"City of Eternal Light": [
		{"id": "cel_herald", "name": "The Sun Sovereign's Herald", "lineage": "Aetherian", "role": "herald", "recruitable": false,
			"portrait_tint": Color(1.0, 0.95, 0.65),
			"schedule": {6: Vector2i(5, 3), 12: Vector2i(15, 10), 18: Vector2i(14, 19), 0: Vector2i(4, 2)},
			"dialogue_tree_id": "cel_herald_default", "quest_hooks": ["cel_false_angel"]},
		{"id": "cel_uri", "name": "Angel-Speaker Uri", "lineage": "Fae-Touched Human", "role": "angel speaker", "recruitable": false,
			"portrait_tint": Color(0.95, 0.95, 0.85),
			"schedule": {6: Vector2i(13, 2), 12: Vector2i(13, 8), 18: Vector2i(14, 19), 0: Vector2i(13, 2)},
			"dialogue_tree_id": "cel_uri_default", "quest_hooks": ["cel_false_angel"]},
		{"id": "cel_vena", "name": "Lightforge Master Vena", "lineage": "Argent Dvarrim", "role": "lightforger", "recruitable": false,
			"portrait_tint": Color(0.85, 0.70, 0.45),
			"schedule": {6: Vector2i(24, 8), 12: Vector2i(24, 8), 18: Vector2i(14, 19), 0: Vector2i(24, 8)},
			"dialogue_tree_id": "cel_vena_default", "quest_hooks": []},
		{"id": "cel_sess", "name": "Divine Merchant Sess", "lineage": "Gilded Human", "role": "relic merchant", "recruitable": false,
			"portrait_tint": Color(1.0, 0.88, 0.55),
			"schedule": {6: Vector2i(8, 13), 12: Vector2i(8, 13), 18: Vector2i(14, 19), 0: Vector2i(8, 13)},
			"dialogue_tree_id": "cel_sess_default", "quest_hooks": []},
		{"id": "cel_barkeep", "name": "Celestial Barkeep Phin", "lineage": "Boreal Human", "role": "barkeep", "recruitable": false,
			"portrait_tint": Color(0.90, 0.80, 0.65),
			"schedule": {6: Vector2i(14, 19), 12: Vector2i(14, 19), 18: Vector2i(14, 19), 0: Vector2i(14, 19)},
			"dialogue_tree_id": "cel_phin_default", "quest_hooks": []},
		{"id": "cel_caen", "name": "Lightbringer Caen", "lineage": "Arcanite Human", "role": "light-mage", "recruitable": false,
			"portrait_tint": Color(0.90, 0.90, 0.70),
			"schedule": {6: Vector2i(20, 10), 12: Vector2i(15, 10), 18: Vector2i(20, 10), 0: Vector2i(14, 19)},
			"dialogue_tree_id": "cel_caen_default", "quest_hooks": []},
		{"id": "cel_mira", "name": "Ascension Guide Mira", "lineage": "Aetherian", "role": "ascension guide", "recruitable": false,
			"portrait_tint": Color(1.0, 1.0, 0.95),
			"schedule": {6: Vector2i(6, 6), 12: Vector2i(6, 6), 18: Vector2i(6, 6), 0: Vector2i(6, 6)},
			"dialogue_tree_id": "cel_mira_default", "quest_hooks": ["cel_false_angel"]},
		{"id": "cel_warden", "name": "Warden of Radiance Kel", "lineage": "Cragborn Human", "role": "warden", "recruitable": false,
			"portrait_tint": Color(0.80, 0.80, 0.65),
			"schedule": {6: Vector2i(20, 2), 12: Vector2i(20, 2), 18: Vector2i(14, 19), 0: Vector2i(20, 2)},
			"dialogue_tree_id": "cel_kel_default", "quest_hooks": []},
	],

	"Hallowed Sacrament": [
		{"id": "hs_cassian", "name": "High Ascendant Cassian", "lineage": "Arcanite Human", "role": "high ascendant", "recruitable": false,
			"portrait_tint": Color(0.90, 0.85, 0.70),
			"schedule": {6: Vector2i(4, 1), 12: Vector2i(4, 3), 18: Vector2i(11, 7), 0: Vector2i(4, 1)},
			"dialogue_tree_id": "hs_cassian_default", "quest_hooks": ["hs_worthy_pilgrim"]},
		{"id": "hs_bevin", "name": "Trial Master Bevin", "lineage": "Cragborn Human", "role": "trial master", "recruitable": false,
			"portrait_tint": Color(0.70, 0.70, 0.60),
			"schedule": {6: Vector2i(10, 5), 12: Vector2i(10, 5), 18: Vector2i(20, 10), 0: Vector2i(10, 5)},
			"dialogue_tree_id": "hs_bevin_default", "quest_hooks": ["hs_worthy_pilgrim"]},
		{"id": "hs_irwyn", "name": "Meditation Master Irwyn", "lineage": "Aetherian", "role": "meditation master", "recruitable": false,
			"portrait_tint": Color(0.90, 0.90, 1.0),
			"schedule": {6: Vector2i(3, 5), 12: Vector2i(11, 7), 18: Vector2i(3, 5), 0: Vector2i(3, 5)},
			"dialogue_tree_id": "hs_irwyn_default", "quest_hooks": []},
		{"id": "hs_odris", "name": "Pilgrim-Priest Odris", "lineage": "Gilded Human", "role": "pilgrim priest", "recruitable": false,
			"portrait_tint": Color(0.95, 0.90, 0.75),
			"schedule": {6: Vector2i(16, 1), 12: Vector2i(4, 3), 18: Vector2i(5, 12), 0: Vector2i(16, 1)},
			"dialogue_tree_id": "hs_odris_default", "quest_hooks": []},
		{"id": "hs_evra", "name": "Sacred Forger Evra", "lineage": "Argent Dvarrim", "role": "sacred forger", "recruitable": false,
			"portrait_tint": Color(0.80, 0.65, 0.40),
			"schedule": {6: Vector2i(18, 5), 12: Vector2i(18, 5), 18: Vector2i(5, 12), 0: Vector2i(18, 5)},
			"dialogue_tree_id": "hs_evra_default", "quest_hooks": []},
		{"id": "hs_sessa", "name": "Vault Keeper Sessa", "lineage": "Fae-Touched Human", "role": "vault keeper", "recruitable": false,
			"portrait_tint": Color(0.85, 0.80, 0.95),
			"schedule": {6: Vector2i(10, 1), 12: Vector2i(10, 1), 18: Vector2i(5, 12), 0: Vector2i(10, 1)},
			"dialogue_tree_id": "hs_sessa_default", "quest_hooks": []},
		{"id": "hs_marmot", "name": "Garden Tender Marmot", "lineage": "Bramblekin", "role": "garden tender", "recruitable": false,
			"portrait_tint": Color(0.55, 0.75, 0.45),
			"schedule": {6: Vector2i(20, 10), 12: Vector2i(20, 10), 18: Vector2i(5, 12), 0: Vector2i(20, 10)},
			"dialogue_tree_id": "hs_marmot_default", "quest_hooks": []},
	],

	# ══════════════════════════════════════════════════════════════════════════
	# SUBLIMINI DOMINUS — 5 NPCs
	# ══════════════════════════════════════════════════════════════════════════

	"Beating Heart of The Void": [
		{"id": "bhv_venn", "name": "Heart-Keeper Venn", "lineage": "Ashenborn", "role": "heart-keeper", "recruitable": false,
			"portrait_tint": Color(0.55, 0.35, 0.45),
			"schedule": {6: Vector2i(10, 9), 12: Vector2i(5, 3), 18: Vector2i(24, 17), 0: Vector2i(10, 9)},
			"dialogue_tree_id": "bhv_venn_default", "quest_hooks": ["bhv_heartbeat"]},
		{"id": "bhv_slix", "name": "Mutation Merchant Slix", "lineage": "Fae-Touched Human", "role": "mutation merchant", "recruitable": false,
			"portrait_tint": Color(0.75, 0.45, 0.65),
			"schedule": {6: Vector2i(6, 12), 12: Vector2i(6, 12), 18: Vector2i(24, 17), 0: Vector2i(6, 12)},
			"dialogue_tree_id": "bhv_slix_default", "quest_hooks": []},
		{"id": "bhv_oorma", "name": "Flesh-Priest Oorma", "lineage": "Gravetouched", "role": "flesh priest", "recruitable": false,
			"portrait_tint": Color(0.60, 0.40, 0.50),
			"schedule": {6: Vector2i(9, 5), 12: Vector2i(10, 9), 18: Vector2i(9, 5), 0: Vector2i(9, 5)},
			"dialogue_tree_id": "bhv_oorma_default", "quest_hooks": ["bhv_heartbeat"]},
		{"id": "bhv_coccoon", "name": "The Coccoon Guardian", "lineage": "Duskling", "role": "coccoon guardian", "recruitable": false,
			"portrait_tint": Color(0.40, 0.35, 0.50),
			"schedule": {6: Vector2i(13, 7), 12: Vector2i(13, 7), 18: Vector2i(13, 7), 0: Vector2i(13, 7)},
			"dialogue_tree_id": "bhv_coccoon_default", "quest_hooks": []},
		{"id": "bhv_karix", "name": "Chitin Forger Karix", "lineage": "Cindervolk", "role": "chitin smith", "recruitable": false,
			"portrait_tint": Color(0.70, 0.45, 0.35),
			"schedule": {6: Vector2i(20, 9), 12: Vector2i(20, 9), 18: Vector2i(24, 17), 0: Vector2i(20, 9)},
			"dialogue_tree_id": "bhv_karix_default", "quest_hooks": []},
	],
}

## Target NPC count per subregion — 184 total when fully authored.
const TARGET_COUNT_BY_SUBREGION: Dictionary = {
	"Upper Forty": 10, "Lower Forty": 10, "Eternal Library": 10,
	"West End Gullet": 10, "Cradling Depths": 10,
	"Kingdom of Qunorum": 8, "Mortal Arena": 8,
	"Wilds of Endero": 6, "Forest of SubEden": 6,
	"Pharaoh's Den": 5,
	"The Darkness": 5, "House of Arachana": 5,
	"Crypt at End of Valley": 5, "Spindle York's Schism": 5,
	"Argent Hall": 5, "Sacral Separation": 5,
	"Depths of Denorim": 6, "Corrupted Marshes": 6,
	"Gloamfen Hollow": 6, "Moroboros": 6,
	"Vulcan Valley": 6, "Infernal Machine": 6,
	"Arcane Collapse": 5, "L.I.T.O.": 5, "Land of Tomorrow": 5,
	"City of Eternal Light": 8, "Hallowed Sacrament": 7,
	"Beating Heart of The Void": 5,
}

static func get_roster(subregion: String) -> Array:
	return REGIONAL_NPCS.get(subregion, [])

## 6..11 -> 6 (morning), 12..17 -> 12 (afternoon), 18..23 -> 18 (evening), 0..5 -> 0 (night)
static func schedule_key_for_hour(hour: int) -> int:
	var h: int = posmod(hour, 24)
	if h >= 6 and h < 12:   return 6
	if h >= 12 and h < 18:  return 12
	if h >= 18:             return 18
	return 0

static func waypoint_for(npc: Dictionary, hour: int) -> Vector2i:
	var sched: Dictionary = npc.get("schedule", {})
	var key: int = schedule_key_for_hour(hour)
	if sched.has(key):
		return sched[key]
	for k in [6, 12, 18, 0]:
		if sched.has(k):
			return sched[k]
	return Vector2i(15, 11)
